project_id = "lvhfwbpivankwzzwvdjj"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.import-enem-questions]
verify_jwt = false

[functions.question-explanation]
verify_jwt = false

[functions.correct-essay]
verify_jwt = false

[functions.ai-study-suggestion]
verify_jwt = false
