project_id = "lvhfwbpivankwzzwvdjj"

[functions.stripe-webhook]
verify_jwt = false

[functions.import-enem-questions]
verify_jwt = false

[functions.question-explanation]
verify_jwt = false

[functions.correct-essay]
verify_jwt = false

[functions.ai-study-suggestion]
verify_jwt = false

[functions.add-manual-question]
verify_jwt = false

[functions.generate-essay-topic]
verify_jwt = false

[functions.analyze-simulado]
verify_jwt = false

[functions.generate-study-schedule]
verify_jwt = false

[functions.extract-question-topic]
verify_jwt = false

[functions.analyze-question-difficulty]
verify_jwt = false

[functions.format-question]
verify_jwt = false

[functions.classify-questions]
verify_jwt = false

[functions.sync-enem-questions]
verify_jwt = false

[functions.classify-and-difficulty]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
